class DemoApi{
 static final List<Map<String, dynamic>> tableData = [
    {
      'Date': '2025-04-16',
      'Account': 'Fiverr',
      'Client Name': 'John Doe',
      'Operation-Status': 'Completed',
      'Sheet link': 'https://example.com/sheet1',
      'Ordered by': 'Admin',
      'Delivery Last Date': '2025-04-20',
      'Profile Status': 'Active',
      'After Fiverr': 'Follow-up done',
      'Tips': '\$10',
      'Rating': '5 Stars',
    },
    {
      'Date': '2025-04-15',
      'Account': 'Upwork',
      'Client Name': 'Jane Smith',
      'Operation-Status': 'Pending',
      'Sheet link': 'https://example.com/sheet2',
      'Ordered by': 'Manager',
      'Delivery Last Date': '2025-04-22',
      'Profile Status': 'Pending',
      'After Fiverr': 'N/A',
      'Tips': '\$0',
      'Rating': 'N/A',
    },
    {
      'Date': '2025-04-14',
      'Account': 'Freelancer',
      'Client Name': 'Alice Cooper',
      'Operation-Status': 'Completed',
      'Sheet link': 'https://example.com/sheet3',
      'Ordered by': 'Team Lead',
      'Delivery Last Date': '2025-04-18',
      'Profile Status': 'Active',
      'After Fiverr': 'Reviewed',
      'Tips': '\$15',
      'Rating': '4 Stars',
    },
    {
      'Date': '2025-04-13',
      'Account': 'Guru',
      'Client Name': 'Bob Marley',
      'Operation-Status': 'Pending',
      'Sheet link': 'https://example.com/sheet4',
      'Ordered by': 'Admin',
      'Delivery Last Date': '2025-04-25',
      'Profile Status': 'Pending',
      'After Fiverr': 'N/A',
      'Tips': '\$5',
      'Rating': '3 Stars',
    },
    {
      'Date': '2025-04-12',
      'Account': 'Toptal',
      'Client Name': 'Charlie Brown',
      'Operation-Status': 'Completed',
      'Sheet link': 'https://example.com/sheet5',
      'Ordered by': 'Manager',
      'Delivery Last Date': '2025-04-17',
      'Profile Status': 'Active',
      'After Fiverr': 'Finalized',
      'Tips': '\$20',
      'Rating': '5 Stars',
    },
  ];

}